#!/usr/bin/python

import socket
import sys
import threading

def run():
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

    sock.connect(("localhost", 45673))

    data = b"x" * 16384

    while True:
        sock.send(data)

        sock.recv(16384)

def main():
    jobs = int(sys.argv[1])

    for i in range(jobs):
        threading.Thread(target=run).start()

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
